# Check for BSA Issue (AEU)

**Purpose:** Code to check if AEU has the BSA issue

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup

```{r, message=FALSE, warning=FALSE}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('programs/DWR-AEU/code/aeu_funcs.R')
source('admin/global_functions/bsa_funcs.R')
source('admin/global_functions/check_funcs.R')
```

## Read in data
```{r}
# specify the file path
data_path <- abs_pesp_path('Groups/DWR-NDFS/02 Processed Data/NDFS_draft.csv')

# read in data
df_data <- read_quiet_csv(data_path) %>%
  mutate(Date = as.Date(Date))

df_micro <- df_data %>%
  filter(Taxon == 'Eucapsis microscopica')
```

# Clean up main taxa issues

```{r}
plot_bsa_check(df_data, cell_col = 'Cells_per_mL', unit_col = 'Units_per_mL')
```

```{r}
plot_bsa_check(df_data, cell_col = 'Cells_per_mL', unit_col = 'Units_per_mL', x_range = c(min(df_micro$Date, na.rm = TRUE),'2014-12-31'))
```

```{r}
check_bsa_issue(df_data, cell_col = 'Cells_per_mL', unit_col = 'Units_per_mL')
```

