```{r}
df_raw <- phyto_taxa
library(tidyverse)
library(stats)
```

```{r}
acf(hood$temp);acf(hood$temp)
```
```{r}
ggplot(example, aes(date, chla, color = station, group = station)) +
  geom_point(size = 4) +
  geom_line(size = 1) +
  theme_bw()
```


```{r}
acf(hood$WIND.SP.MPH)
```


```{r}
extract_species <- function(taxon) {
  # Split the Taxon into words
  words <- unlist(strsplit(taxon, " "))
  
  # Check if "var." is present
  if ("var." %in% words) {
    # Extract the word right before "var." and any remaining words
    species_index <- which(words == "var.") - 1
    paste(words[species_index:length(words)], collapse = " ")
  } else {
    # If "var." is not present, take the last word as the species
    words[length(words)]
  }
}

# Apply the function in a mutate statement
df <- df_raw %>%
  mutate(Species = sapply(Taxon, extract_species),
         Taxon = gsub("\\bcf\\.\\s*", "", Taxon))

df <- df %>% distinct(Kingdom, Phylum, Class, AlgalGroup, Genus, Species, Taxon, .keep_all = TRUE)

write_csv(df, 'C:/Users/sperry/Desktop/phyto_taxa.csv')
```

