# Check Metadata

```{r}
devtools::load_all()
```

```{r}
df_pesp <- read_csv(abs_pesp_path('Synthesized Dataset/02 Processed Data/PESP_dataset.csv'))
```

# Check Columns

## Survey
```{r}
unique_check(df_pesp, Survey)
```

```{r}
names(df_pesp)
```

## Sample Scheme
```{r}
unique_check(df_pesp, SampleScheme)
```

# Check Sample Methods
```{r}
unique_check(df_pesp, SampleMethod)
```

# Check Dates
```{r}
all(is.na(as.Date(df_pesp$Date)) == FALSE)
```

# Check lat/lon

Valid at all
```{r}
all(df_pesp$Latitude >= -90 & df_pesp$Latitude <= 90 | is.na(df_pesp$Latitude)) &
all(df_pesp$Longitude >= -180 & df_pesp$Longitude <= 180 | is.na(df_pesp$Longitude))
```

In the estuary
```{r}
all(df_pesp$Latitude >= 36 & df_pesp$Latitude <= 39 | is.na(df_pesp$Latitude)) &
all(df_pesp$Longitude <= -121 & df_pesp$Longitude >= -122.6 | is.na(df_pesp$Longitude))

test2 <- filter(df_pesp, is.na(Longitude))
# all missing coordinates are from known events
```

# Check if station names are repeated in different surveys

```{r}
stations_multi_loc <- df_pesp %>%
  distinct(Station, Location) %>%
  group_by(Station) %>%
  summarise(
    n_locations = n(),
    locations = toString(unique(Location)),
    .groups = 'drop'
  ) %>%
  filter(n_locations > 1)

stations_multi_loc
```

# Sample depth
```{r}
unique_check(df_pesp, SampleDepth)
```

```{r}
uk_depth <- df_pesp %>% filter(is.na(SampleDepth))
uk_depth
unique(uk_depth$SampleMethod)
```

# Lab
```{r}
unique_check(df_pesp, Lab)
```

# Magnification
```{r}
unique_check(df_pesp, Magnification)
```

# Count Methods
```{r}
unique_check(df_pesp, CountMethodSample)
```

```{r}
unique_check(df_pesp, CountMethodTaxa)
```

```{r}
unique_check(df_pesp, PhytoForm)
```


# QC Codes
```{r}
qc_check <- df_pesp %>%
 separate_rows(QualityCheck, sep = ' ') %>%
 filter(!is.na(QualityCheck) & QualityCheck != '') %>%
 group_by(Survey, QualityCheck) %>%
 summarize(count = n(), .groups = 'drop') %>%
 left_join(
   df_pesp %>% group_by(Survey) %>% summarize(total_samples = n()),
   by = 'Survey'
 ) %>%
 mutate(percentage = round(count / total_samples * 100, 2)) %>%
 select(-count, -total_samples) %>%
 pivot_wider(names_from = Survey, values_from = percentage, values_fill = 0)

qc_check
```

```{r}
debris_check <- df_pesp %>%
  separate_rows(Debris, sep = ' ') %>%
  mutate(
    Debris = Debris %>%
      str_remove_all('[[:punct:]]') %>%
      str_squish() %>%
      na_if('') 
  ) %>%
  filter(!is.na(Debris)) %>%
  group_by(Survey, Debris) %>%
  summarize(count = n(), .groups = 'drop') %>%
  left_join(
    df_pesp %>% group_by(Survey) %>% summarize(total_samples = n()),
    by = 'Survey'
  ) %>%
  mutate(percentage = round(count / total_samples * 100, 2)) %>%
  select(-count, -total_samples) %>%
  pivot_wider(names_from = Survey, values_from = percentage, values_fill = 0)

debris_check
```

```{r}
notes_check <- df_pesp %>%
 separate_rows(Notes, sep = ' ') %>%
 filter(!is.na(Notes) & Notes != '') %>%
 group_by(Survey, Notes) %>%
 summarize(count = n(), .groups = 'drop') %>%
 left_join(
   df_pesp %>% group_by(Survey) %>% summarize(total_samples = n()),
   by = 'Survey'
 ) %>%
 mutate(percentage = round(count / total_samples * 100, 2)) %>%
 select(-count, -total_samples) %>%
 pivot_wider(names_from = Survey, values_from = percentage, values_fill = 0)

notes_check
```

# Taxa
```{r}
unique_check(df_pesp, Kingdom)
```

```{r}
unique_check(df_pesp, Phylum)
```

```{r}
unique_check(df_pesp, Class)
```

```{r}
unique_check(df_pesp, AlgalGroup)
```

```{r}
any(is.na(df_pesp$Genus))
```

```{r}
any(is.na(df_pesp$Species))
```

```{r}
df_dupes <- df_pesp %>%
  group_by(Event_ID, CountMethodTaxa, Kingdom, Phylum, Class, AlgalGroup, Genus, Species, Taxon) %>%
  filter(n()  > 1) %>%
  ungroup()

df_dupes
# check for any issues with taxonomy

lookup <- select(df_pesp, Phylum, Class, AlgalGroup) %>%
  distinct() %>%
  arrange(Phylum, Class,AlgalGroup)
```

#check cells per L greater than units per l
```{r}
testunits <- df_pesp %>%
  filter(
    Cells_per_mL < Units_per_mL &
      !str_detect(QualityCheck, 'UnitsExceedCells')
  )
testunits
```


#QA codes

```{r}
unique(df_pesp$QualityCheck)
```
