# Synthesize Datasets

```{r}
library(tidyverse)
source('admin/global_functions/global_funcs.R')
```

## Synthesize data
```{r}
data_dir <- here::here('synthesized', '02_group_data')
fp_data <- list.files(data_dir, pattern = '\\.Rdata$', full.names = TRUE)
ls_combined <- list()

for (file in fp_data) {
  env <- new.env()
  load(file, envir = env)
  obj_name <- ls(env)
  
  df <- get(obj_name, envir = env)
  df <- df %>%
    mutate(across(-any_of('Date'), as.character))
  ls_combined[[file]] <- df
}

df_pesp <- dplyr::bind_rows(ls_combined)

nrow(df_pesp) == sum(sapply(ls_combined, nrow))
```

## Fix SampleMethod names
```{r}
rename_map <- c('unspecified surface grab' = 'unspecified grab sample')

df_pesp <- rename_values(df_pesp, 'SampleMethod', rename_map)
```

## Fix Survey names
```{r}
rename_map <- c('CDFW-STN' = 'STN',
                'CDFW-FMWT' = 'FMWT')

df_pesp <- rename_values(df_pesp, 'Survey', rename_map)
```

## Fix depths
```{r}
rename_map <- c('1' = '1 meter')

df_pesp <- rename_values(df_pesp, 'SampleDepth', rename_map)
```

## Set unknown surface depths to 0 (for filtering)
```{r}
# df_pesp <- df_pesp %>%
#  mutate(SampleDepth = case_when(
#    SampleMethod %in% c('unspecified surface grab','putty knife') & is.na(SampleDepth) ~ '0',
#    TRUE ~ SampleDepth
#    )
#  )
```

## Remove unneeded cols
```{r}
df_pesp <- df_pesp %>% select(-c(TowNetRadius)) # same for everyone
```

```{r}
df_pesp <- df_pesp %>% arrange(Survey, Date, Station)
```

## Write
```{r}
write_csv(df_pesp, abs_pesp_path('Synthesized Dataset/02 Processed Data/PESP_dataset.csv'))
```