# Format original BGC data

**Purpose:** Code to format BGC data for original PESP upload.

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup

```{r}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('programs/USGS-BGC/code/bgc_funcs.R')
source('admin/global_functions/check_funcs.R')
```

```{r}
# Read in Data --------------------------------------------------------------------
# specify the file path
data_path <- abs_data_path('Component data sets/USGS-BGC/USGS_Phytoenumeration_2016topresent-20230622ER.csv')

# new data to format and append
df_data <- read_quiet_csv(data_path)

# standardize data
df_data <- standardize_cols_bgc(df_data)

df_data <- add_meta_col(df_data, 'USGS BGC', 'SamplingDepth')

df_data <- add_meta_col(df_data, 'USGS BGC', 'Lab')

df_data <- clean_unknowns(df_data)

df_data <- add_qc_col(df_data)

df_data <- subset_cols_bgc(df_data)

# # Add in Higher Level Taxa ------------------------------------------------------
df_joined <- higher_lvl_taxa(df_data, 'SamplingDepth')

df_filltaxa <- check_higher_taxa(df_joined)
```

```{r}
# # Update Names ------------------------------------------------------------------
df_joined <- update_synonyms(df_joined)

df_fillsyn <- check_synonyms(df_joined)
```

```{r}
# Data Checks ---------------------------------------------------------------------
# check collection type variables
check_methods(df_joined)
```

```{r}
# check for duplicates
df_dupes <- check_distinct(df_joined)
```

```{r}
# check if no data observed
check_nodata(df_joined)
```

```{r}
# remove other rows with no data

remove_nodata <- function(df) {
  df_nodat <- df %>% filter(Cells_per_mL == 0 & Biovolume_per_mL == 0)

  count_rm <- nrow(df_nodat)
  
  print(paste('Removed', count_rm, 'rows with no data on:',
              paste(df_nodat$Station, df_nodat$Date, sep = ' ', collapse = '; ')))

  df_filtered <- df %>% filter(!(Cells_per_mL == 0 & Biovolume_per_mL == 0))
    
  return(df_filtered)
}

df_joined <- remove_nodata(df_joined)
```


## Export

```{r}
write_csv(df_joined, 'programs/USGS-BGC/data/phyto_data_BGC.csv')
```
