```{r}
library(tidyverse)
library(vegan)
library(lubridate)
source('admin/global_functions/global_funcs.R')
source('admin/global_functions/check_funcs.R')
```

```{r}
df_phyto <- read_quiet_csv('programs/USGS-BGC/data/phyto_data_BGC.csv') %>%
  mutate(Year = year(Date)) %>%
  group_by(Station) %>%
  mutate(FirstYear = min(Year)) %>%
  ungroup() %>%
  mutate(StationFirstYear = paste(FirstYear, Station, sep = " ")) %>%
  select(-FirstYear)

# create_nmds(df_phyto, 'Date', 'Cells_per_mL', 'Year')
create_nmds(df_phyto, 'StationFirstYear', 'Cells_per_mL', show_legend = FALSE)

df_nmds <- create_nmds(df_phyto, 'StationFirstYear', 'Cells_per_mL', show_legend = FALSE)[[1]]
```


```{r}
create_nmds(df_phyto, 'Date', 'Cells_per_mL', 'Year')
```
```{r}

df_cells <- df_data %>%
  select('Station', Taxon, 'Cells_per_mL') %>%
  group_by(Station, Taxon) %>%
  reframe(Cells_per_mL = mean(Cells_per_mL, na.rm = TRUE)) %>%
  pivot_wider(names_from = Taxon, values_from = Cells_per_mL)


com <- df_cells %>%
  select(-Station)
com[is.na(com)] <- 0
m_com <- as.matrix(com)

nmds <- metaMDS(m_com, distance = 'bray')
df_nmds <- as.data.frame(scores(nmds)$sites)

df_nmds <- df_nmds %>%
  mutate(Station = df_cells %>% pull(Station)) %>%
  mutate(Station = as.factor(Station))

plt_nmds <- ggplot(df_nmds, aes(x = NMDS1, y = NMDS2, group = Station)) + 
  geom_point(size = 4, shape = 21, color = '#000000', aes(fill = Station)) +
  # scale_fill_brewer(palette ='Set1') +
  theme_bw() +
  theme(legend.position="none")
  

plt_nmds
```

```{r}
plt_nmds <- function(df, group_var, nmds_var, factor_var) {
  set.seed(42)
  
  df_cells <- df %>%
    select({{group_var}}, {{factor_var}}, Taxon, {{nmds_var}}) %>%
    group_by({{group_var}}, {{factor_var}}, Taxon) %>%
    reframe({{nmds_var}} := mean({{nmds_var}}, na.rm = TRUE)) %>%
    pivot_wider(names_from = Taxon, values_from = {{nmds_var}})
  
  
  
  com <- df_cells %>%
    select(-{{group_var}}, -{{factor_var}})
  com[is.na(com)] <- 0
  m_com <- as.matrix(com)
  
  nmds <- metaMDS(m_com, distance = 'bray')
  df_nmds <- as.data.frame(scores(nmds)$sites)
  
  df_nmds <- df_nmds %>%
    mutate({{factor_var}} := df_cells %>% pull({{factor_var}})) %>%
    mutate({{factor_var}} := as.factor({{factor_var}}))
  
  # Create the plot
  plt_nmds <- ggplot(df_nmds, aes(x = NMDS1, y = NMDS2, group = {{factor_var}})) + 
    geom_point(size = 4, shape = 21, color = '#000000', aes(fill = {{factor_var}})) +
    scale_fill_brewer(palette ='Set1') +
    theme_bw()
  
  return(plt_nmds)
}
```

