# Check EMP data

**Purpose:** Code to check EMP data for errors

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

```{r}
library(tidyverse)
library(vegan)
library(lubridate)
source('admin/global_functions/global_funcs.R')
source('admin/global_functions/check_funcs.R')
set.seed(42)
```

```{r}
load('synthesized/02_group_data/DWR-EMP.RData')

# format main dataframe (species unit)
df_phyto <- df_emp %>%
  mutate(Date = parse_date_time(Date, orders = c('ymd', 'dmy', 'mdy')),
         Year = factor(year(Date)),
         Event = paste(Date, Station, sep = '_'),
         Binary = 1)

# format df (genus unit)
df_genus <- df_phyto %>%
  group_by(Date, Year, Event, Station, Genus, Lab, CountMethodSample) %>%
  summarize(Biovolume_per_mL = sum(Biovolume_per_mL),
            Cells_per_mL = sum(Cells_per_mL),
            Units_per_mL = sum(Units_per_mL),
            .groups = 'drop') %>%
  mutate(Binary = 1)


df_bv_species <- df_phyto %>%
  filter(!is.na(Biovolume_per_mL))

df_bv_genus <- df_genus %>%
  filter(!is.na(Biovolume_per_mL))
```

# Check BSA Issue

```{r}
check_bsa_issue(df_phyto, cell_col = 'Cells_per_mL', unit_col = 'Units_per_mL')
```


# NMDS by Species

### Biovol
```{r}
# create NMDS
df_bv <- calc_nmds(df_bv_species,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Biovolume_per_mL')

# print plot
plt_nmds <- plot_nmds(df_bv$df_nmds, df_bv$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Biovol_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_bv$df_nmds, df_bv$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Biovol_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_bv$df_nmds, df_bv$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Biovol_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

### Units
```{r}
# create NMDS
df_unit <- calc_nmds(df_phyto,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Units_per_mL')

# print plot
plt_nmds <- plot_nmds(df_unit$df_nmds, df_unit$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Units_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_unit$df_nmds, df_unit$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Units_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_unit$df_nmds, df_unit$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Units_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

### Cells
```{r}
# create NMDS
df_cell <- calc_nmds(df_phyto,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Cells_per_mL')

# print plot
plt_nmds <- plot_nmds(df_cell$df_nmds, df_cell$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Cells_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_cell$df_nmds, df_cell$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Cells_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_cell$df_nmds, df_cell$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Cells_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

### PA
```{r}
# create NMDS
df_pa <- calc_nmds(df_phyto,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Binary',
                      distance = 'jaccard')

# print plot
plt_nmds <- plot_nmds(df_pa$df_nmds, df_pa$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_PA_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_pa$df_nmds, df_pa$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_PA_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_pa$df_nmds, df_pa$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_PA_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

# NMDS by Genus and Date

### Biovol
```{r}
# create NMDS
df_bv <- calc_nmds(df_bv_genus,
                      taxa_var = 'Genus',                    
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Biovolume_per_mL')

# print plot
plt_nmds <- plot_nmds(df_bv$df_nmds, df_bv$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_Biovol_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_bv$df_nmds, df_bv$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_Biovol_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_bv$df_nmds, df_bv$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_Biovol_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

### Units
```{r}
# create NMDS
df_unit <- calc_nmds(df_genus,
                      taxa_var = 'Genus',
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Units_per_mL')

# print plot
plt_nmds <- plot_nmds(df_unit$df_nmds, df_unit$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Units_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_unit$df_nmds, df_unit$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Units_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_unit$df_nmds, df_unit$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Species_Units_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

### Cells
```{r}
# create NMDS
df_cell <- calc_nmds(df_genus,
                      taxa_var = 'Genus',                    
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Cells_per_mL')

# print plot
plt_nmds <- plot_nmds(df_cell$df_nmds, df_cell$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_Cells_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_cell$df_nmds, df_cell$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_Cells_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_cell$df_nmds, df_cell$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_Cells_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

### PA
```{r}
# create NMDS
df_pa <- calc_nmds(df_genus,
                      taxa_var = 'Genus',                    
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','Lab','CountMethodSample'),
                      nmds_var = 'Binary',
                      distance = 'jaccard')

# print plot
plt_nmds <- plot_nmds(df_pa$df_nmds, df_pa$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_PA_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_pa$df_nmds, df_pa$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_PA_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_pa$df_nmds, df_pa$meta_vars, fill_var = 'CountMethodSample')
plt_nmds

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_Genus_PA_CountMethod.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

# Check Counts
```{r}
plt_count <- check_station_count(df_phyto)

plt_count

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_HM_StationNumber.jpg'),
  plot = plt_count,
  width = 8,
  height = 5
)
```

```{r}
plt_freq <- check_sampling_freq(df_phyto)

plt_freq

ggsave(
  filename = abs_pesp_path('Synthesized Dataset/01 Group Checks/DWR-EMP/graphs/EMP-Synth_HM_SampFreq.jpg'),
  plot = plt_freq,
  width = 8,
  height = 5
)
```