# Synthesize Datasets

```{r, message=FALSE, warning=FALSE}
# import packages
devtools::load_all()
```

## Synthesize data
```{r}
data_dir <- here::here('admin/standardized_data')
fp_data <- list.files(data_dir, pattern = '\\.Rda$', full.names = TRUE)
ls_combined <- list()

for (file in fp_data) {
  env <- new.env()
  load(file, envir = env)
  obj_name <- ls(env)
  
  df <- get(obj_name, envir = env)
  df <- df %>%
    mutate(across(-any_of('Date'), as.character))
  ls_combined[[file]] <- df
}

df_pesp <- dplyr::bind_rows(ls_combined)

nrow(df_pesp) == sum(sapply(ls_combined, nrow))
```

## Fix SampleMethod names
```{r}
rename_map <- c('unspecified surface grab' = 'unspecified grab sample')

df_pesp <- rename_values(df_pesp, 'SampleMethod', rename_map)
```

## Fix Survey names
```{r}
rename_map <- c('CDFW-STN' = 'STN',
                'CDFW-FMWT' = 'FMWT')

df_pesp <- rename_values(df_pesp, 'Survey', rename_map)
```

## Fix depths
```{r}
rename_map <- c('1' = '1 meter')

df_pesp <- rename_values(df_pesp, 'SampleDepth', rename_map)
```

## Remove unneeded cols
```{r}
df_pesp <- df_pesp %>% select(-c(TowNetRadius)) # same for everyone
```

## Arrange cols
```{r}
df_pesp <- df_pesp %>% arrange(Survey, Date, Station)
```

## Remove rows with no data
```{r}
df_pesp <- remove_nodata(df_pesp)
no_data <- attr(df_pesp, 'log')$nodata
```
## Convert density columns to numeric
```{r}
df_pesp <- df_pesp %>%
  mutate(across(contains('per_mL'), ~ as.numeric(.)))
```

## Check for outliers
```{r}
# Cells per mL
df_pesp <- flag_outliers(df_pesp, Cells_per_mL)
```


```{r}
# Units per mL
df_pesp <- flag_outliers(df_pesp, Units_per_mL)
```

```{r}
# Biovolume per mL
df_pesp <- flag_outliers(df_pesp, Biovolume_per_mL, cutoff = 3.5)
```


## Write
```{r}
write_csv(df_pesp, abs_pesp_path('Synthesized Dataset/02 Processed Data/PESP_dataset.csv'))
```