# Format original AEU data

**Purpose:** Code to format AEU data for original PESP upload.

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup

```{r, message=FALSE, warning=FALSE}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('programs/DWR-AEU/code/aeu_funcs.R')
source('admin/global_functions/bsa_funcs.R')
source('admin/global_functions/check_funcs.R')
```

```{r}
# # Read in Data --------------------------------------------------------------------
# specify the file path
data_path <- abs_data_path('Component data sets/DWR AEU/dwr-aeu-2020.csv')

# data frame containing Tiffany Brown's standardized phyto taxa csv
df_syn <- read_quiet_csv('admin/global_data/phyto_classifications_extra.csv')

# read in metadata sheet
df_meta <- read_meta_file('Yolo Bypass Fish Monitoring Program')

# new data to format and append
df_data <- read_quiet_csv(data_path)

# standardize data
df_data <- standardize_cols_aeu(df_data, df_meta)

df_data <- clean_unknowns(df_data)

df_data <- add_qc_col(df_data)

df_data <- add_debris_col(df_data)

df_data <- subset_cols_aeu(df_data)

# add different dilution code for data before/including 2020
df_data <- add_dilution_qc(df_data)

# # Add in Higher Level Taxa ------------------------------------------------------
df_joined <- higher_lvl_taxa(df_data, after_col = 'Lab')

df_filltaxa <- check_higher_taxa(df_joined)

# # Update Names ------------------------------------------------------------------
df_joined <- update_synonyms(df_joined)

df_fillsyn <- check_synonyms(df_joined)

# # Check Collection Type Variables -----------------------------------------------
check_methods(df_joined)

# # Subset Columns ----------------------------------------------------------------
# Check
df_dupes <- check_distinct(df_joined, return_df = TRUE)

df_joined %>% distinct() %>% nrow()
```

## Export

```{r}
write_csv(df_joined, 'programs/DWR-AEU/data/phyto_data_AEU.csv')
```
