# Check AEU data

**Purpose:** Code to check AEU data for errors

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

```{r}
library(tidyverse)
library(vegan)
library(lubridate)
source('admin/global_functions/global_funcs.R')
source('admin/global_functions/check_funcs.R')
```

```{r}
df_phyto <- read_quiet_csv('programs/DWR-AEU/data/phyto_data_AEU.csv') %>%
  mutate(Year = year(Date)) %>%
  mutate(StationYear = paste(Year, Station, sep = ' '))

# create_nmds(df_phyto, 'Date', 'Cells_per_mL', 'Year')
create_nmds(df_phyto, 'Year', 'Cells_per_mL')

df_nmds <- create_nmds(df_phyto, 'Year', 'Cells_per_mL')[[1]]
```

```{r}
df_phyto <- read_quiet_csv('programs/DWR-AEU/data/phyto_data_AEU.csv') %>%
  mutate(Year = year(Date)) %>%
  mutate(StationYear = paste(Year, Station, sep = ' '))

# create_nmds(df_phyto, 'Date', 'Cells_per_mL', 'Year')
create_nmds(df_phyto, 'StationYear', 'Cells_per_mL')

df_nmds <- create_nmds(df_phyto, 'StationYear', 'Cells_per_mL')[[1]]
```

