# Prep NDFS Data

**Purpose:** Prep NDFS data for PESP merge.

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup
```{r, message=FALSE, warning=FALSE}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('admin/global_functions/syn_funcs.R')
source('admin/global_functions/bsa_funcs.R')
source('admin/global_functions/check_funcs.R')
```

# Read in data
```{r}
# specify the file path
data_path_NDFS <- abs_pesp_path('Groups/DWR-NDFS/03 Final Data/NDFS_draft_all.csv')

# new data to format and append
df_ndfs <- read_quiet_csv(data_path_NDFS)
```

# Clean data

## Convert Time (if needed)
TODO: come back to this when metadata is in

## Add in Metadata
```{r}
# Survey
df_ndfs <- add_meta_col(df_ndfs, 'DWR-NDFS', 'Survey')

# Sample Method
df_ndfs <- add_meta_col(df_ndfs, 'DWR-NDFS', 'SampleMethod')

# Magnification
df_ndfs <- df_ndfs %>%
  mutate(Magnification = NA_character_) # TODO: fix when metadata is in

# Depth Type
df_ndfs <- add_meta_col(df_ndfs, 'DWR-NDFS', 'DepthType')

# Sample Scheme
df_ndfs <- add_meta_col(df_ndfs, 'DWR-NDFS', 'SampleScheme')
```


## Add extra columns
```{r}
df_ndfs <- df_ndfs %>% 
  mutate(TowNetRadius = NA)
```

## Subset relevant columns
```{r}
df_ndfs <- subset_cols(df_ndfs, remove_cols = c('Location','GALD','PhytoForm'))
```

## Save .Rdata
```{r}
save(df_ndfs, file = 'synthesized/group_prep/group_data/DWR-NDFS.Rdata')
```

