# Prep BP Data

**Purpose:** Prep BP data for PESP merge.

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup
```{r, message=FALSE, warning=FALSE}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('admin/global_functions/syn_funcs.R')
source('admin/global_functions/bsa_funcs.R')
source('admin/global_functions/check_funcs.R')
```

# Read in data
```{r}
# specify the file path
data_path_bp <- abs_pesp_path('Groups/USGS-BP/02 Processed Data/BP_draft_all.csv')

# new data to format and append
df_bp <- read_quiet_csv(data_path_bp)
```

# Clean data

## Add in Metadata
```{r}
# Survey
df_bp <- add_meta_col(df_bp, 'USGS-BP', 'Survey')

# Magnification
df_bp <- add_meta_col(df_bp, 'USGS-BP', 'Magnification') # FIX HOW THIS WORKS

# Depth Type
df_bp <- df_bp %>% mutate(DepthType = 
                            case_when(Depth_m <= 2 ~ 'near surface',
                                      Depth_m > 2 ~ 'mid-depth'))

# Sample Scheme
df_bp <- add_meta_col(df_bp, 'USGS-BP', 'SampleScheme')
```

## Add extra columns
```{r}
df_bp <- df_bp %>% 
  rename(TowNetRadius = NetRadius_cm,
         SampleDepth = Depth_m) %>%
  mutate(Time = NA,
         Units_per_mL = NA)
```

## Subset relevant columns
```{r}
df_bp <- subset_cols(df_bp, remove_cols = c('Location','GALD','PhytoForm'))
```


## Save .Rdata
```{r}
save(df_bp, file = 'synthesized/group_prep/group_data/USGS-BP.Rdata')
```


