```{r}
library(tidyverse)
library(vegan)
library(lubridate)
source('admin/global_functions/global_funcs.R')
source('admin/global_functions/check_funcs.R')
```

```{r}
df_ndfs <- read_quiet_csv(abs_pesp_path('Groups/DWR-NDFS/02 Processed Data/NDFS_draft.csv'))  %>%
  mutate(Year = year(Date),
         Month = month(Date)) %>%
  mutate(StationYear = paste(Year, Station, sep = ' '),
         MonthYear = paste(Month, Year, sep = ' '))

df_aeu <- read_quiet_csv(abs_pesp_path('Groups/DWR-AEU/02 Processed Data/AEU_draft.csv')) %>%
  mutate(Year = year(Date),
         Month = month(Date)) %>%
  mutate(StationYear = paste(Year, Station, sep = ' '),
         MonthYear = paste(Month, Year, sep = ' '))

# Step 1: Find common MonthYear values
shared_months <- intersect(df_aeu$MonthYear, df_ndfs$MonthYear)

# Step 2: Subset both dataframes to shared MonthYears
df_aeu <- df_aeu %>% filter(MonthYear %in% shared_months)
df_ndfs <- df_ndfs %>% filter(MonthYear %in% shared_months)

# create NMDS
df_nmds_ndfs <- create_nmds(df_ndfs,
                        group_var = 'MonthYear',
                        nmds_var = 'Cells_per_mL',
                        factor_var = 'Year')

# create NMDS
df_nmds_aeu <- create_nmds(df_aeu,
                        group_var = 'MonthYear',
                        nmds_var = 'Cells_per_mL',
                        factor_var = 'Year')

pro <- procrustes(df_nmds_ndfs$raw_nmds, df_nmds_aeu$raw_nmds)
pro
protest(df_nmds_ndfs$raw_nmds, df_nmds_aeu$raw_nmds, permutations = 999)

test <- df_nmds_ndfs$raw_nmds
```

```{r}
shared_months
```

