# Check BP data

**Purpose:** Code to check BP data for errors

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

```{r}
library(tidyverse)
library(vegan)
library(lubridate)
source('admin/global_functions/global_funcs.R')
source('admin/global_functions/check_funcs.R')
set.seed(42)
```

```{r}
# format main dataframe (species unit)
df_phyto <- read_quiet_csv(abs_pesp_path('Groups/USGS-BP/02 Processed Data/BP_draft_all.csv')) %>%
  mutate(Date = parse_date_time(Date, orders = c('ymd', 'dmy')),
         Year = factor(year(Date)),
         Binary = 1)

# format df (genus unit)
df_genus <- df_phyto %>%
  group_by(Date, Year, Station, SampleMethod, Lab, Genus) %>%
  summarize(Biovolume_per_mL = sum(Biovolume_per_mL),
            Cells_per_mL = sum(Cells_per_mL),
            .groups = 'drop') %>%
  mutate(Binary = 1)
```

# NMDS by Species and Date

## Biovol
```{r}
# create NMDS
df_nmds_bv <- calc_nmds(df_phyto,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','SampleMethod','Lab'),
                      nmds_var = 'Biovolume_per_mL')

# print plot
plt_nmds <- plot_nmds(df_nmds_bv$df_nmds, df_nmds_bv$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_Biovolume_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_bv$df_nmds, df_nmds_bv$meta_vars, fill_var = 'SampleMethod')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_Biovolume_Method.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_bv$df_nmds, df_nmds_bv$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_Biovolume_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

## Cells
```{r}
# create NMDS
df_nmds_cell <- calc_nmds(df_phyto,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','SampleMethod','Lab'),
                      nmds_var = 'Cells_per_mL')

# print plot
plt_nmds <- plot_nmds(df_nmds_cell$df_nmds, df_nmds_cell$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_Cells_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_cell$df_nmds, df_nmds_cell$meta_vars, fill_var = 'SampleMethod')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_Cells_Method.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_cell$df_nmds, df_nmds_cell$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_Cells_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

## PA
```{r}
# create NMDS
df_nmds_pa <- calc_nmds(df_phyto,
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','SampleMethod','Lab'),
                      nmds_var = 'Binary',
                      distance = 'jaccard')

# print plot
plt_nmds <- plot_nmds(df_nmds_pa$df_nmds, df_nmds_pa$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_PA_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_pa$df_nmds, df_nmds_pa$meta_vars, fill_var = 'SampleMethod')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_PA_Method.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_pa$df_nmds, df_nmds_pa$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Species_PA_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

# NMDS by Genus
## Biovol
```{r}
# create NMDS
df_nmds_bv <- calc_nmds(df_genus,
                      taxa_var = 'Genus',                    
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','SampleMethod','Lab'),
                      nmds_var = 'Biovolume_per_mL')

# print plot
plt_nmds <- plot_nmds(df_nmds_bv$df_nmds, df_nmds_bv$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_Biovolume_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_bv$df_nmds, df_nmds_bv$meta_vars, fill_var = 'SampleMethod')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_Biovolume_Method.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_bv$df_nmds, df_nmds_bv$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_Biovolume_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

## Cells
```{r}
# create NMDS
df_nmds_cell <- calc_nmds(df_genus,
                      taxa_var = 'Genus',                    
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','SampleMethod','Lab'),
                      nmds_var = 'Cells_per_mL')

# print plot
plt_nmds <- plot_nmds(df_nmds_cell$df_nmds, df_nmds_cell$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_Cells_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_cell$df_nmds, df_nmds_cell$meta_vars, fill_var = 'SampleMethod')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_Cells_Method.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_cell$df_nmds, df_nmds_cell$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_Cells_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```

## PA
```{r}
# create NMDS
df_nmds_pa <- calc_nmds(df_genus,
                      taxa_var = 'Genus',                    
                      group_var = 'Date',
                      avg_var = 'Station',
                      factor_var = c('Year','SampleMethod','Lab'),
                      nmds_var = 'Binary',
                      distance = 'jaccard')

# print plot
plt_nmds <- plot_nmds(df_nmds_pa$df_nmds, df_nmds_pa$meta_vars, fill_var = 'Year')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_PA_Year.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_pa$df_nmds, df_nmds_pa$meta_vars, fill_var = 'SampleMethod')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_PA_Method.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)

# print plot
plt_nmds <- plot_nmds(df_nmds_pa$df_nmds, df_nmds_pa$meta_vars, fill_var = 'Lab')
plt_nmds

ggsave(
  filename = abs_pesp_path('Groups/USGS-BP/02 Processed Data/QC files/graphs/BP_NMDS_Genus_PA_Lab.jpg'),
  plot = plt_nmds,
  width = 8,
  height = 6
)
```