# Format original Bay Program data

**Purpose:** Code to format Bay Program data for original PESP upload.

**Author:** Perry ([sarah.perry\@water.ca.gov](mailto:sarah.perry@water.ca.gov){.email})

# Initial Setup

```{r, message=FALSE, warning=FALSE}
# Import Packages ---------------------------------------------------------
library(tidyverse)
library(fuzzyjoin)
library(glue)
library(lubridate)

source('admin/global_functions/global_funcs.R')
source('programs/USGS-BP/code/bp_funcs.R')
source('admin/global_functions/bsa_funcs.R')
source('admin/global_functions/check_funcs.R')
```

First File

```{r}
# # Read in Data --------------------------------------------------------------------
# specify the file path
data_path <- abs_data_path('Component data sets/SF Bay Peterson Project/PhytoUSGSDufford_April1992-March2014.csv')

# data frame containing Tiffany Brown's standardized phyto taxa csv
df_syn <- read_quiet_csv('admin/global_data/phyto_classifications.csv')

# new data to format and append
df_data_duf <- read_quiet_csv(data_path)

df_data_duf <- rename_cols_bp(df_data_duf, 'Dufford')

# TODO: add in sampling method
df_data_duf$SamplingMethod <- 'unknown' 

# standardize data
df_data_duf <- standardize_cols_bp(df_data_duf, df_meta)
```

```{r}
# # Add in Higher Level Taxa ------------------------------------------------------
df_joined_duf <- higher_lvl_taxa(df_data_duf, after_col = 'Lab')

df_filltaxa <- check_higher_taxa(df_joined_duf) # TODO:  add export = TRUE

# # Update Names ------------------------------------------------------------------
df_joined_duf <- update_synonyms(df_joined_duf)

df_fillsyn <- check_synonyms(df_joined_duf)

# # Check Collection Type Variables -----------------------------------------------
check_methods(df_joined_duf)

# # Subset Columns ----------------------------------------------------------------
# Check
df_dupes <- check_distinct(df_joined_duf, return_df = TRUE)

df_joined_duf <- distinct(df_joined_duf)

df_joined_duf$QualityCheck <- NA

df_joined_duf$Debris <- NA

df_joined_duf <- df_joined_duf %>% select(-Notes)
```

Second File

```{r}
# # Read in Data --------------------------------------------------------------------
# specify the file path
data_path <- abs_data_path('Component data sets/SF Bay Peterson Project/PhytoUSGSBSA_Jan2014-April2023_notes.csv')

# data frame containing Tiffany Brown's standardized phyto taxa csv
df_syn <- read_quiet_csv('admin/global_data/phyto_classifications.csv')

# new data to format and append
df_data_bsa <- read_quiet_csv(data_path)

df_data_bsa <- rename_cols_bp(df_data_bsa, 'BSA')
  
# TODO: add in sampling method
df_data_bsa$SamplingMethod <- 'unknown' 

# standardize data
df_data_bsa <- standardize_cols_bp(df_data_bsa, df_meta)

df_data_bsa <- add_qc_col(df_data_bsa, 'Notes')

df_data_bsa <- add_debris_col(df_data_bsa, 'Notes')
```

```{r}
# # Add in Higher Level Taxa ------------------------------------------------------
df_joined_bsa <- higher_lvl_taxa(df_data_bsa, after_col = 'Lab')

df_filltaxa <- check_higher_taxa(df_joined_bsa) # TODO:  add export = TRUE

write_csv(df_filltaxa, 'C:/Users/sperry/Desktop/taxa2.csv')

# # Update Names ------------------------------------------------------------------
df_joined_bsa <- update_synonyms(df_joined_bsa)

df_fillsyn <- check_synonyms(df_joined_bsa)

# # Check Collection Type Variables -----------------------------------------------
check_methods(df_joined_bsa)

# # Check Duplicate Rows ----------------------------------------------------------
# Check
df_dupes <- check_distinct(df_joined_bsa, return_df = TRUE)

# # Subset Columns ----------------------------------------------------------------
df_joined_bsa <- subset_cols_bp(df_joined_bsa)
```

Third File

```{r}
# # Read in Data --------------------------------------------------------------------
# specify the file path
data_path <- abs_data_path('Component data sets/SF Bay Peterson Project/PhytoUSGS_Net_Oct2017-Nov2022_notes.csv')

# data frame containing Tiffany Brown's standardized phyto taxa csv
df_syn <- read_quiet_csv('admin/global_data/phyto_classifications.csv')

# new data to format and append
df_data_net <- read_quiet_csv(data_path)

df_data_net <- rename_cols_net(df_data_net, 'BSA')
  
# TODO: add in sampling method
df_data_net$SamplingMethod <- 'unknown' 

df_data_net$Depth_m <- NA

# standardize data
df_data_net <- standardize_cols_bp(df_data_net, df_meta)

df_data_net <- add_qc_col(df_data_net, 'Notes')

df_data_net <- add_debris_col(df_data_net, 'Notes')
```

```{r}
# # Add in Higher Level Taxa ------------------------------------------------------
df_joined_net <- higher_lvl_taxa(df_data_net, after_col = 'Lab')

df_filltaxa <- check_higher_taxa(df_joined_net) # TODO:  add export = TRUE

write_csv(df_filltaxa, 'C:/Users/sperry/Desktop/taxa3.csv')

# # Update Names ------------------------------------------------------------------
df_joined_net <- update_synonyms(df_joined_net)

df_fillsyn <- check_synonyms(df_joined_net)

# # Check Collection Type Variables -----------------------------------------------
check_methods(df_joined_net)

# # Check Duplicate Rows ----------------------------------------------------------
# Check
df_dupes <- check_distinct(df_joined_net, return_df = TRUE)

# # Subset Columns ----------------------------------------------------------------
df_joined_net <- subset_cols_bp(df_joined_net)
```

## Export

```{r}
df_joined <- bind_rows(df_joined_net, df_joined_bsa)
df_joined <- bind_rows(df_joined, df_joined_duf)

df_joined <- df_joined %>%
  arrange(Date, Station, Taxon) %>%
  mutate(Date = as.Date(Date))

write_csv(df_joined, 'programs/USGS-BP/data/BP_Phyto_Data.csv')
```
