name: Run package tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::testthat
            any::rcmdcheck
          cache: true
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Run R CMD check (show errors)
        run: |
          Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--as-cran', '--timings'), error_on = 'error', check_dir = 'check', build_args = '--no-resave-data', quiet = FALSE)"

