name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("testthat", "tidyverse", "rlang"))'
      
      - name: Run tests
        run: |
          Rscript tests/testthat.R