name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # check out repo
      - uses: actions/checkout@v4

      # set up R environment
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      # install dependencies automatically based on DESCRIPTION
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check

      # run tests using testthat
      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests/testthat", reporter = "summary")'
