# .github/workflows/tests.yml
name: Run package tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install EDIutils manually
        run: |
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('EDIorg/EDIutils', upgrade = 'never')"
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::testthat
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: Rscript -e 'devtools::test()'

