# Check Metadata

```{r}
library(tidyverse)
source('admin/global_functions/global_funcs.R')
source('admin/global_functions/check_funcs.R')
```

```{r}
df_pesp <- read_csv(abs_pesp_path('Synthesized Dataset/02 Processed Data/PESP_dataset.csv'))
```

# Check Columns

## Survey
```{r}
unique_check(df_pesp, Survey)
```

```{r}
names(df_pesp)
```
## Sample Scheme
```{r}
unique_check(df_pesp, SampleScheme)
```

# Check Sample Methods
```{r}
unique_check(df_pesp, SampleMethod)
```

# Check Dates
```{r}
all(is.na(as.Date(df_pesp$Date)) == FALSE)
```

# Check lat/lon
```{r}
all(df_pesp$Latitude >= -90 & df_pesp$Latitude <= 90 | is.na(df_pesp$Latitude)) &
all(df_pesp$Longitude >= -180 & df_pesp$Longitude <= 180 | is.na(df_pesp$Longitude))
```
That checks whether the lats and longs are valid, but are they in the estuary?
```{r}
all(df_pesp$Latitude >= 36 & df_pesp$Latitude <= 39 | is.na(df_pesp$Latitude)) &
all(df_pesp$Longitude >= -121 & df_pesp$Longitude <= -122.6 | is.na(df_pesp$Longitude))

test = filter(df_pesp,Longitude <= -122.6 |  Longitude >= -121 )
#Ahah! Someone forgot to make longitude negative
test2 = filter(df_pesp, is.na(Longitude))
#what's up with the missing GPS coordinates?
```


```{r}
unique_check(df_pesp, SampleDepth)
```

```{r}
uk_depth <- df_pesp %>% filter(is.na(SampleDepth))
uk_depth
unique(uk_depth$SampleMethod)
```

```{r}
unique_check(df_pesp, Lab)
```

```{r}
unique_check(df_pesp, Magnification)
```


```{r}
unique_check(df_pesp, CountMethodSample)
```

```{r}
unique_check(df_pesp, CountMethodTaxa)
```

```{r}
qc_check <- df_pesp %>%
 separate_rows(QualityCheck, sep = ' ') %>%
 filter(!is.na(QualityCheck) & QualityCheck != '') %>%
 group_by(Survey, QualityCheck) %>%
 summarise(count = n(), .groups = 'drop') %>%
 left_join(
   df_pesp %>% group_by(Survey) %>% summarise(total_samples = n()),
   by = 'Survey'
 ) %>%
 mutate(percentage = round(count / total_samples * 100, 2)) %>%
 select(-count, -total_samples) %>%
 pivot_wider(names_from = Survey, values_from = percentage, values_fill = 0)

qc_check
```

```{r}
debris_check <- df_pesp %>%
 separate_rows(Debris, sep = ' ') %>%
 filter(!is.na(Debris) & Debris != '') %>%
 group_by(Survey, Debris) %>%
 summarise(count = n(), .groups = 'drop') %>%
 left_join(
   df_pesp %>% group_by(Survey) %>% summarise(total_samples = n()),
   by = 'Survey'
 ) %>%
 mutate(percentage = round(count / total_samples * 100, 2)) %>%
 select(-count, -total_samples) %>%
 pivot_wider(names_from = Survey, values_from = percentage, values_fill = 0)

debris_check
```

```{r}
notes_check <- df_pesp %>%
 separate_rows(Notes, sep = ' ') %>%
 filter(!is.na(Notes) & Notes != '') %>%
 group_by(Survey, Notes) %>%
 summarise(count = n(), .groups = 'drop') %>%
 left_join(
   df_pesp %>% group_by(Survey) %>% summarise(total_samples = n()),
   by = 'Survey'
 ) %>%
 mutate(percentage = round(count / total_samples * 100, 2)) %>%
 select(-count, -total_samples) %>%
 pivot_wider(names_from = Survey, values_from = percentage, values_fill = 0)

notes_check
```

```{r}
unique_check(df_pesp, Kingdom)
```

```{r}
unique_check(df_pesp, Phylum)
```

```{r}
unique_check(df_pesp, Class)
```

```{r}
unique_check(df_pesp, AlgalGroup)
```

```{r}
any(is.na(df_pesp$Genus))
```

```{r}
any(is.na(df_pesp$Species))
```

```{r}
df_dupes <- df_pesp %>%
  group_by(Event_ID, Kingdom, Phylum, Class, AlgalGroup, Genus, Species, Taxon) %>%
  filter(n()  > 1) %>%
  ungroup()

df_dupes
# check for any issues with taxonomy

lookup = select(df_pesp, Phylum, Class, AlgalGroup) %>%
  distinct() %>%
  arrange(Phylum, Class,AlgalGroup)

```

#check cells per L greater than units per l


```{r}
all(df_pesp$Cells_per_mL > df_pesp$Units_per_mL | is.na(df_pesp$Cells_per_mL)) 

testunits = filter(df_pesp, Cells_per_mL < Units_per_mL)
#Some of these are already noted as "Units exceeds cells" but not all of them.
```

#QA codes

```{r}
unique(df_pesp$QualityCheck)
```
